#!/bin/sh

BUILD=0

HELP_MESSAGE="
Usage: ./generate_compile_commands [OPTIONS]

Generate compile commands for clangd. The following options are supported:

  --build                  Build the project to also generate protobuf files.
  -h|--help                Show this help message.
"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --build) BUILD=1; shift 1;;
    -h|--help) echo "$HELP_MESSAGE"; exit 0;;
  esac
done

sudo mkdir /ws && sudo ln -s /src /ws/src
sudo chown ubuntu:ubuntu /ws
cd /ws && mkdir build
cmake -B build -S src -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_TESTING=ON -DBUILD_PROTOCOL=ON
if [ $BUILD -eq 1 ]; then
  cmake --build build -j $(( `nproc` > 1 ? `nproc` - 1 : num_cores ))
fi
cp build/compile_commands.json /src