FROM ghcr.io/aica-technology/control-libraries/development-dependencies:latest

# Copy and set the entrypoint commands to execute when the container starts
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
