name: Build and Push Multi-Arch Images

on:
  push:
    branches:
      - develop
      - main
      - patch/v7.4.1
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - image: ubuntu-latest
          # FIXME: using 4vcpu image because of heavy RAM usage when building pinoccio on arm64
          - image: buildjet-4vcpu-ubuntu-2204-arm
            arch: arm64

    runs-on: ${{ matrix.image }}
    name: Build and publish (${{ matrix.arch }})
    steps:
      - uses: actions/checkout@v3

      - uses: aica-technology/.github/.github/actions/list-add-suffixes@v0.6.1
        id: merge-tags
        with:
          list: v7.4.1
          suffixes: ${{ matrix.arch }}
          glue_separator: "-"

      - uses: aica-technology/.github/.github/actions/ghcr-build@v0.6.1
        with:
          image_name: aica-technology/control-libraries
          image_tags: ${{ steps.merge-tags.outputs.list }}
          dockerfile_path: Dockerfile
          token: ${{ secrets.GITHUB_TOKEN }}

  multi-arch:
    runs-on: ubuntu-latest
    name: Merge into a multi-arch image
    needs: [build]
    steps:
      - uses: aica-technology/.github/.github/actions/ghcr-manifest-merge@v0.6.1
        with:
          image_name: aica-technology/control-libraries
          image_tags: v7.4.1
          archs: amd64,arm64
          token: ${{ secrets.GITHUB_TOKEN }}
