name: Build and Push

# Run workflow on pushes to main branch or by manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish-proto-dependencies-focal-fossa:
    name: Build and publish proto dependencies image on ubuntu 20.04
    uses: aica-technology/.github/.github/workflows/build-push-multi-arch.yml@ed4ba3f4327b2a61948cde7b4e9410363114c478
    with:
      image_name: ${{ github.repository }}/proto-dependencies
      image_tags: 20.04
      build_context_path: .
      dockerfile_path: Dockerfile.proto
      platforms: linux/amd64
      build_flags: '--build-arg BASE_TAG=20.04'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-publish-proto-dependencies-jammy-jellyfish:
    name: Build and publish proto dependencies image on ubuntu 22.04
    uses: aica-technology/.github/.github/workflows/build-push-multi-arch.yml@ed4ba3f4327b2a61948cde7b4e9410363114c478
    with:
      image_name: ${{ github.repository }}/proto-dependencies
      image_tags: 22.04,latest
      build_context_path: .
      dockerfile_path: Dockerfile.proto
      platforms: linux/amd64,linux/arm64
      build_flags: '--build-arg BASE_TAG=22.04'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-publish-development-dependencies-focal-fossa:
    needs: build-publish-proto-dependencies-focal-fossa
    uses: aica-technology/.github/.github/workflows/build-push-multi-arch.yml@ed4ba3f4327b2a61948cde7b4e9410363114c478
    with:
      image_name: ${{ github.repository }}/development-dependencies
      image_tags: 20.04
      build_context_path: .
      dockerfile_path: Dockerfile.base
      platforms: linux/amd64
      build_flags: '--build-arg BASE_TAG=20.04'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-publish-development-dependencies-jammy-jellyfish:
    needs: build-publish-proto-dependencies-jammy-jellyfish
    uses: aica-technology/.github/.github/workflows/build-push-multi-arch.yml@ed4ba3f4327b2a61948cde7b4e9410363114c478
    with:
      image_name: ${{ github.repository }}/development-dependencies
      image_tags: 22.04,latest
      build_context_path: .
      dockerfile_path: Dockerfile.base
      platforms: linux/amd64,linux/arm64
      build_flags: '--build-arg BASE_TAG=22.04'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
